# hiclass-api의 pod 수를 자동으로 조절한다.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hi-class-api-hpa
  namespace: default
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hi-class-api
  targetCPUUtilizationPercentage: 50 # target CPU utilization
