apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-class-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hi-class-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hi-class-ui
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: hi-class-ui
        image: hiclass.azurecr.io/hi-class-ui:latest
        ports:
        - containerPort: 19082
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /
            port: 19082
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 19082
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hi-class-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 19082
  selector:
    app: hi-class-ui
